In [2]:
import numpy as np

In [3]:
np.version.version

'1.26.4'

In [25]:
# help(np)

#### Creating One Dimensional Array

In [5]:
vector_a = np.array([1,2,3])
vector_a

array([1, 2, 3])

In [6]:
type(vector_a)

numpy.ndarray

In [7]:
vector_a.dtype

dtype('int32')

In [9]:
vector_b = np.array([1, 2, 'a'])
vector_b

array(['1', '2', 'a'], dtype='<U11')

### List in array should be even number

In [11]:
list_even = [i for i in range (1,21) if i%2==0]
list_even

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [13]:
numpy_even = np.array(list_even)
numpy_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
#shortcut technique where if else is multiple steps are not used
numpy_evenn = np.array([i for i in range (2,21,2)])
numpy_evenn

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Multidimensional array

In [22]:
two_dimesional_array = np.array([[1,2] 
                                ,[3,4]])
two_dimesional_array.shape

(2, 2)

In [24]:
multi = np.array([1,2,3], [3,4,5,6]) #throws error, matirx not dimensionally correct
multi.shape

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [29]:
multi_d = np.array([1,2,3], ndmin=5)
print(multi_d)
print(multi_d.shape)

[[[[[1 2 3]]]]]
(1, 1, 1, 1, 3)


In [31]:
#to take 2 from this array
multi_d[0][0][0][0][1]

2

### Making Matrix

In [34]:
mat_a = np.mat([[1,2], [3,4]])
mat_a

matrix([[1, 2],
        [3, 4]])

In [38]:
mat_a.shape

(2, 2)

#### Arrays with Arange

In [39]:
arange_a = np.arange(20)
arange_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
#multiple of 7 from 0 to 100
multiple_seven = np.arange(7, 100, 7)
multiple_seven

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

#### Creating arrays of ones, zeros and empty

In [44]:
zero_demo = np.zeros((3))
zero_demo

array([0., 0., 0.])

In [45]:
multi_zero = np.zeros((3,4))
multi_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
int_zero = np.zeros((4,4), dtype=int)
int_zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
change_to_ten = 10*np.ones((10))
change_to_ten

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [56]:
slice_b = np.arange(20)
slice_b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Slicer

In [58]:
slice_b[10:25] = 1
slice_b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [60]:
#copy can be used for not changing the acutal value
slicerr = np.arange(20)
slicerr
slicerCopy = np.copy(slicerr)
slicerCopy[10:25]= 40
slicerCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40])

In [62]:
slice_multi_dimesnsional = np.array([[1,2,3], [4,5,6]])
slice_multi_dimesnsional[:,0]

array([1, 4])

In [64]:
slice_multi_dimesnsional[:,0:2]

array([[1, 2],
       [4, 5]])

In [63]:
slice_multi_dimesnsional[:][0]

array([1, 2, 3])

### Boolean Indexing

In [67]:
bool_a = np.array([[1,2], [3,4], [5,6]])
bool_idx = (bool_a > 2)
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [68]:
bool_a[bool_idx]

array([3, 4, 5, 6])

In [72]:
bool_b = np.array(['python', 'Java', 'Ruby', 'Rust'])
bool_b == 'Python'

array([False, False, False, False])

In [78]:
#either python or ruby
(bool_b == 'python') | (bool_b == 'Ruby')

array([ True, False,  True, False])

In [77]:
bool_greater_than_ten = np.array([1,2,3,4,5,60, 70,2, 40, 60])
bool_indx = (bool_greater_than_ten > 10)
print(bool_indx)
print(bool_greater_than_ten[bool_indx])

[False False False False False  True  True False  True  True]
[60 70 40 60]


#### Keep value of 10 students, want marks of student with marks greater than 60 and less and 80

In [87]:
student_info = np.array([50, 60, 80, 65, 70, 78, 60, 59, 66, 68])
student_satisfying_criteria = ((student_info >= 60) & (student_info <= 80))
student_info[student_satisfying_criteria]

array([60, 80, 65, 70, 78, 60, 66, 68])

In [92]:
x = np.array([1,2,3])
y = np.array([1,2]) #should have equal value for addition
x + y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

#### Transposing matrix

In [93]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])